#! /bin/sh

nm-applet &
nitrogen --restore &
picom --experimental-backends &
sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor eDP-1 -d I II III IV V VI VII
bspc monitor DP-1 -d I II III IV V VI VII

bspc config border_width         1
bspc config window_gap          15
bspc config top_padding		40
bspc config bottom_padding 0

if [[ $(polybar -m | tail -1 | sed -e 's/:.*$//g') == "DP-1" ]]; then
	xrandr --output DP-1 --primary --mode 1920x1080 --rate
75 --output eDP-1 --off
	nitrogen --restore &
	bspc config bottom_padding 120
fi

#BSPWM coloring
 
bspc config normal_border_color		"#121212"
bspc config active_border_color		"#121212"
bspc config focused_border_color	"#964c53"
bspc config presel_feedback_color	"#964c53"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

#bspwm rules

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a Brave-browser-nightly desktop='V'
bspc rule -a Ferdi desktop='VII'
bspc rule -a discord desktop='VII'
bspc rule -a Gimp-2.10 desktop='IV'
bspc rule -a wps desktop='IV'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


